# Fast Scan Configuration Example
# Optimized for speed over thoroughness - use for quick network discovery
# Trade-offs: May miss some devices or services, less detailed information

arp:
  timeout: 1                    # Reduced timeout for faster scanning
  retries: 1                    # Minimal retries
  interface: null               # Auto-detect interface
  method: "scapy"              # Fast and reliable method
  parallel_threads: 20          # High parallelism for speed

nmap:
  scan_type: "-sT"             # TCP connect scan (no root required)
  port_range: "-F"             # Fast scan (top 100 ports only)
  timing: "-T5"                # Insane timing (fastest)
  os_detection: ""             # Skip OS detection (slow)
  service_detection: ""        # Skip service detection (slow)
  additional_flags:            # Minimal flags for speed
    - "--min-rate=1000"        # High packet rate
    - "--max-retries=1"        # Minimal retries
  timeout: 120                 # Shorter timeout
  max_parallel: 100            # High parallelism

snmp:
  versions: [2]                # Only try SNMPv2c (fastest)
  communities:                 # Only try common community
    - "public"
  timeout: 3                   # Short timeout
  retries: 1                   # No retries
  max_oids_per_request: 50     # Large batches for efficiency
  max_walk_oids: 25            # Limit data collection
  walk_oids: []                # No walks, only specific OIDs
  specific_oids:               # Only essential information
    - oid: "1.3.6.1.2.1.1.1.0"
      name: "sysDescr"
      description: "System description"
    - oid: "1.3.6.1.2.1.1.5.0"
      name: "sysName"
      description: "System name"

# Expected scan time for /24 network: 60-120 seconds
# Use case: Quick network inventory, initial discovery