# Network Discovery Configuration
# Configurazione principale per il modulo Discovery Engine PMI Dashboard EPS

network:
  # Target network range (CIDR notation)
  target_range: "192.168.1.0/24"
  
  # Additional specific hosts
  additional_hosts: []
    # - "10.0.0.1"
    # - "172.16.0.0/16"
  
  # Exclusions
  exclude_ranges: []
    # - "192.168.1.100-192.168.1.110"
  
  # DNS servers for hostname resolution
  dns_servers:
    - "8.8.8.8"
    - "1.1.1.1"

# ARP Discovery Settings
arp_discovery:
  enabled: true
  ping_sweep: true
  timeout_seconds: 1
  max_parallel_pings: 50
  ping_count: 1

# NMAP Configuration - Scansione completa e approfondita
nmap:
  enabled: true
  
  # Modalità scansione
  scan_mode: "comprehensive"  # basic, standard, comprehensive, aggressive
  
  # Host discovery options
  host_discovery:
    methods: ["ping", "arp", "syn"]
    timeout: "5s"
    max_rate: 1000
    ping_types: ["icmp", "tcp-syn", "tcp-ack"]
  
  # Port scanning options
  port_scan:
    enabled: true
    scan_type: "syn"  # syn, connect, udp
    
    # Port ranges - Scansione completa e approfondita
    tcp_ports:
      - "1-1024"      # System ports completi
      - "1433,1521,3306,5432"  # Database (SQL Server, Oracle, MySQL, PostgreSQL)
      - "3389,5900,5901,5902"  # RDP, VNC variants
      - "8080,8443,8000,8008,8081,8888"  # Web services alternative
      - "2049,2121,2222"  # NFS, FTP-data, SSH alternative
      - "27017,6379"  # MongoDB, Redis (PostgreSQL già incluso sopra)
      - "9200,9300"   # Elasticsearch
      - "5601,5672"   # Kibana, RabbitMQ
      - "8086,9000"   # InfluxDB, SonarQube
      - "10000-10010" # Custom/Enterprise services
      - "49152-49162" # Dynamic/Private ports
      - "5985,5986"   # WinRM HTTP/HTTPS
    
    udp_ports:
      - "53,67,68,69,123,161,162,514"  # DNS, DHCP, TFTP, NTP, SNMP, Syslog
      - "1194,4500,500"  # OpenVPN, IPSec
      - "1900,5353"   # UPnP, mDNS
      - "137,138,139" # NetBIOS
    
    # Performance settings - Ottimizzato per scansioni complete
    timing_template: 3  # Normale (bilanciato velocità/accuratezza)
    max_parallelism: 50 # Ridotto per evitare sovraccarico di rete
    timeout: "15s"      # Timeout più lungo per servizi lenti
    max_retries: 3      # Più tentativi per maggiore affidabilità
  
  # Service detection - Detection più approfondito
  service_detection:
    enabled: true
    version_intensity: 9  # Intensità massima (0-9)
    version_light: false  # Non usare detection leggero
    probe_all_ports: true # Prova detection su tutte le porte aperte
    version_all: true     # Abilita detection su tutte le porte
    
  # OS detection - Più aggressivo per migliori risultati
  os_detection:
    enabled: true
    aggressive: true    # Abilita detection più aggressivo
    osscan_limit: false # Scan sempre, anche con poche porte  
    osscan_guess: true  # Prova a indovinare anche con info limitate
    
  # Script scanning - Solo safe scripts
  scripts:
    enabled: true
    categories: ["safe"]
    custom_scripts: []

# SNMP Configuration (v1/v2c only)
snmp:
  enabled: true
  
  # Connection settings
  port: 161
  timeout_seconds: 5
  retries: 3
  max_parallel: 20
  
  # Protocol versions to try
  versions: ["2c", "1"]  # Try v2c first, then v1
  
  # Community strings to test
  communities:
    - "public"
    - "private"
    - "community"
    - "admin"
    - "manager"
    - "read"
    - "monitor"
  
  # OID Collections
  oids:
    # System Information (Always collected)
    system_info:
      sysDescr: "1.3.6.1.2.1.1.1.0"
      sysObjectID: "1.3.6.1.2.1.1.2.0"
      sysUpTime: "1.3.6.1.2.1.1.3.0"
      sysContact: "1.3.6.1.2.1.1.4.0"
      sysName: "1.3.6.1.2.1.1.5.0"
      sysLocation: "1.3.6.1.2.1.1.6.0"
      sysServices: "1.3.6.1.2.1.1.7.0"
    
    # Interface Information
    interfaces:
      walk_base: "1.3.6.1.2.1.2.2.1"
      collect_stats: true
      specific_oids:
        ifNumber: "1.3.6.1.2.1.2.1.0"
    
    # Performance Metrics
    performance:
      enabled: true
      cpu_oids:
        - "1.3.6.1.4.1.2021.11.9.0"      # NET-SNMP CPU idle
        - "1.3.6.1.4.1.9.9.109.1.1.1.1.7.1"  # Cisco CPU 5min
      memory_oids:
        - "1.3.6.1.4.1.2021.4.6.0"       # NET-SNMP available memory
        - "1.3.6.1.4.1.9.9.48.1.1.1.5.1" # Cisco memory used
    
    # Vendor specific collections
    vendor_specific:
      cisco:
        enabled: true
        temperature: "1.3.6.1.4.1.9.9.13.1.3.1.3"
        fan_status: "1.3.6.1.4.1.9.5.1.4.1.1.4"
        power_supply: "1.3.6.1.4.1.9.9.13.1.5.1.3"
      
      hp:
        enabled: true
        sensor_status: "1.3.6.1.4.1.11.2.14.11.5.1.9.6.1.0"
        health_status: "1.3.6.1.4.1.11.2.14.11.5.1.9.1.1.4"

# Output Settings
output:
  format: "json"
  file: "discovery_results.json"
  pretty_print: true
  indent: 2
  include_raw_data: false
  include_timestamps: true
  
  # Additional outputs (disabilitato)
  additional_formats: []
    # - format: "csv"
    #   file: "devices.csv"
    #   fields: ["ip_address", "hostname", "device_type", "vendor"]

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "discovery.log"
  max_size_mb: 10
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Component specific logging
  components:
    arp: "INFO"
    nmap: "DEBUG"
    snmp: "INFO"

# Performance Settings
performance:
  max_concurrent_scans: 5
  memory_limit_mb: 512
  scan_timeout_minutes: 30
  
  # Rate limiting to avoid network overload
  rate_limit:
    requests_per_second: 100
    burst_size: 200
    
  # Threading
  thread_pool_size: 10
  max_workers: 50

# Security Settings
security:
  # Network considerations
  respect_rate_limits: true
  stealth_mode: false
  randomize_scan_order: false
  
  # Data handling
  mask_communities_in_output: true
  secure_temp_files: true
  
  # Scan ethics
  max_scan_rate: 1000  # packets per second
  avoid_fragmentation: true
