# Standard MIB-II OIDs (RFC 1213)
# Definizioni OID per il Discovery Engine PMI Dashboard EPS

standard:
  system:
    sysDescr: 
      oid: "1.3.6.1.2.1.1.1.0"
      description: "A textual description of the entity"
      type: "DisplayString"
    sysObjectID: 
      oid: "1.3.6.1.2.1.1.2.0"
      description: "The vendor's authoritative identification"
      type: "OBJECT IDENTIFIER"
    sysUpTime: 
      oid: "1.3.6.1.2.1.1.3.0"
      description: "Time since last reinitialization"
      type: "TimeTicks"
    sysContact: 
      oid: "1.3.6.1.2.1.1.4.0"
      description: "Contact person for this managed node"
      type: "DisplayString"
    sysName: 
      oid: "1.3.6.1.2.1.1.5.0"
      description: "Administratively assigned name"
      type: "DisplayString"
    sysLocation: 
      oid: "1.3.6.1.2.1.1.6.0"
      description: "Physical location of this node"
      type: "DisplayString"
    sysServices: 
      oid: "1.3.6.1.2.1.1.7.0"
      description: "Value indicating the set of services"
      type: "INTEGER"

  interfaces:
    ifNumber:
      oid: "1.3.6.1.2.1.2.1.0"
      description: "Number of network interfaces"
      type: "INTEGER"
    ifIndex:
      oid: "1.3.6.1.2.1.2.2.1.1"
      description: "Interface index"
      type: "INTEGER"
    ifDescr:
      oid: "1.3.6.1.2.1.2.2.1.2"
      description: "Interface description"
      type: "DisplayString"
    ifType:
      oid: "1.3.6.1.2.1.2.2.1.3"
      description: "Interface type"
      type: "INTEGER"
    ifMtu:
      oid: "1.3.6.1.2.1.2.2.1.4"
      description: "Interface MTU"
      type: "INTEGER"
    ifSpeed:
      oid: "1.3.6.1.2.1.2.2.1.5"
      description: "Interface speed in bits per second"
      type: "Gauge32"
    ifPhysAddress:
      oid: "1.3.6.1.2.1.2.2.1.6"
      description: "Interface physical address"
      type: "PhysAddress"
    ifAdminStatus:
      oid: "1.3.6.1.2.1.2.2.1.7"
      description: "Interface administrative status"
      type: "INTEGER"
    ifOperStatus:
      oid: "1.3.6.1.2.1.2.2.1.8"
      description: "Interface operational status"
      type: "INTEGER"
    ifInOctets:
      oid: "1.3.6.1.2.1.2.2.1.10"
      description: "Octets received"
      type: "Counter32"
    ifOutOctets:
      oid: "1.3.6.1.2.1.2.2.1.16"
      description: "Octets transmitted"
      type: "Counter32"
    ifInErrors:
      oid: "1.3.6.1.2.1.2.2.1.14"
      description: "Input errors"
      type: "Counter32"
    ifOutErrors:
      oid: "1.3.6.1.2.1.2.2.1.20"
      description: "Output errors"
      type: "Counter32"

# Vendor-specific OIDs
vendor:
  cisco:
    system:
      ciscoCPU5Min:
        oid: "1.3.6.1.4.1.9.9.109.1.1.1.1.7.1"
        description: "5 minute CPU utilization"
        type: "Gauge32"
      ciscoMemoryPoolUsed:
        oid: "1.3.6.1.4.1.9.9.48.1.1.1.5.1"
        description: "Memory pool bytes used"
        type: "Gauge32"
      ciscoMemoryPoolFree:
        oid: "1.3.6.1.4.1.9.9.48.1.1.1.6.1"
        description: "Memory pool bytes free"
        type: "Gauge32"
      ciscoEnvMonTemperatureStatusValue:
        oid: "1.3.6.1.4.1.9.9.13.1.3.1.3"
        description: "Current temperature reading"
        type: "Gauge32"
      
    hardware:
      ciscoFanStatus:
        oid: "1.3.6.1.4.1.9.5.1.4.1.1.4"
        description: "Fan operational status"
        type: "INTEGER"
      ciscoPowerSupplyStatus:
        oid: "1.3.6.1.4.1.9.9.13.1.5.1.3"
        description: "Power supply status"
        type: "INTEGER"

  hp:
    system:
      hpSystemHealthStat:
        oid: "1.3.6.1.4.1.11.2.14.11.5.1.9.1.1.4"
        description: "Overall system health status"
        type: "INTEGER"
      hpSensorStatus:
        oid: "1.3.6.1.4.1.11.2.14.11.5.1.9.6.1.0"
        description: "Sensor status"
        type: "INTEGER"

  netsnmp:
    system:
      nsCPUIdle:
        oid: "1.3.6.1.4.1.2021.11.11.0"
        description: "Percentage of CPU idle time"
        type: "INTEGER"
      nsMemAvailReal:
        oid: "1.3.6.1.4.1.2021.4.6.0"
        description: "Available real/physical memory in KB"
        type: "INTEGER"
      nsMemTotalReal:
        oid: "1.3.6.1.4.1.2021.4.5.0"
        description: "Total real/physical memory in KB"
        type: "INTEGER"

# Common port-to-service mappings for service identification
services:
  tcp:
    22: "ssh"
    23: "telnet"
    25: "smtp"
    53: "domain"
    80: "http"
    110: "pop3"
    143: "imap"
    443: "https"
    993: "imaps"
    995: "pop3s"
    3389: "ms-wbt-server"
    5900: "vnc"
    8080: "http-proxy"
    8443: "https-alt"
  udp:
    53: "domain"
    67: "bootps"
    68: "bootpc"
    69: "tftp"
    123: "ntp"
    161: "snmp"
    162: "snmptrap"
    514: "syslog"
